name: assets_picker
description: assets picker
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker: ^7.1.0
  wechat_camera_picker: ^3.0.4
  extended_image: ^6.0.2+1
  photo_manager: ^2.0.7
  video_player: ^2.3.0
  fl_video: ^0.0.3
  image: ^3.1.3
  wakelock: ^0.6.1+2

dev_dependencies:
  flutter_lints: ^1.0.4
